#!/bin/bash

set -x

while getopts p:o:n:u:i: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        o) origin=${OPTARG};;
        n) name=${OPTARG};;
        u) username=${OPTARG};;
        i) keyfile=${OPTARG};;
    esac
done

# DNS machine
scp -i ${keyfile} ./dnsserver ${username}@cs5700cdnproject.ccs.neu.edu:~/

# Cache machines
scp -i ${keyfile} httpserver popular_pages_20201130.csv ${username}@ec2-34-238-192-84.compute-1.amazonaws.com:~/
scp -i ${keyfile} httpserver popular_pages_20201130.csv ${username}@ec2-13-231-206-182.ap-northeast-1.compute.amazonaws.com:~/
# scp -i ${keyfile} httpserver popular_pages_20201130.csv ${username}@ec2-13-239-22-118.ap-southeast-2.compute.amazonaws.com
# scp -i ${keyfile} httpserver popular_pages_20201130.csv ${username}@ec2-34-248-209-79.eu-west-1.compute.amazonaws.com
# scp -i ${keyfile} httpserver popular_pages_20201130.csv ${username}@ec2-18-231-122-62.sa-east-1.compute.amazonaws.com
# scp -i ${keyfile} httpserver popular_pages_20201130.csv ${username}@ec2-3-101-37-125.us-west-1.compute.amazonaws.com
